[package]
name = "cli_todo_list"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.33", features = ["derive"] }
dialoguer = "0.11.0"
figlet-rs = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
